### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [boriswerner/ioBroker.midi#2]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/boriswerner/ioBroker.midi

- [ ] [E145] No news found for actual version 0.0.4

I have also found warnings that may be fixed if possible.

- [ ] [W400] Cannot find "midi" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by boriswerner** [comment]
Adapter added to NPM
- [X] [E201] bluefox added as owner in npm
- [ ] [E300] to be done
- [X] [E802] topics have been setup
- [ ] [W400] to be done after [E300]

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by boriswerner** [comment]
Failed checks:
- [ ] [E145] No news found for actual version 0.0.4
- [ ] [E301] Tests on Travis-ci.org are broken. Please fix.
- [ ] [W400] Cannot find "midi" in latest repository
Will check it together with https://github.com/boriswerner/ioBroker.midi/issues/9

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
